### ISSUE TITLE
为什么我打包的插件jar自己的idea本地导入正常能用给别人用不了呢？

### ISSUE THREAD

**Issue by lt9** [yangfeng20/idea-plugin-dev-guide#1]
把打包好的插件jar发送给他人后，他人在与我相同版本的idea中导入jar，显示安装成功，工具栏也出现了插件新增的菜单，但是用的时候一点反应没有。
插件的action的第一行都进入不了。

**Comment by yangfeng20** [comment]
可能是你的插件报错了。在执行action中报错了，就没有反应。至于你本地可以使用，可能是你代码的问题，兼容性可能有问题。例如使用了某某环境变量之类的，这里只是举一个例子哈。
要怎么看是不是报错了呢，你把idea开一下内部模式，然后观察idea右下角。

![image](https://github.com/user-attachments/assets/47413a06-9ea8-442c-88ae-e74b0382e305)

**Comment by lt9** [comment]
> 可能是你的插件报错了。在执行action中报错了，就没有反应。至于你本地可以使用，可能是你代码的问题，兼容性可能有问题。例如使用了某某环境变量之类的，这里就举一个例子哈。 要怎么看是不是报错了呢，你把idea开一下内部模式，然后观察idea右下角。
> 
> ![图像](https://private-user-images.githubusercontent.com/83114564/351936616-47413a06-9ea8-442c-88ae-e74b0382e305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzUzMDgsIm5iZiI6MTcyMTg3NTAwOCwicGF0aCI6Ii84MzExNDU2NC8zNTE5MzY2MTYtNDc0MTNhMDYtOWVhOC00NDJjLTg4YWUtZTc0YjAzODJlMzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyMzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NTlmYmNlNjFiYTkyOTNjMzI4Y2IyZWE2OGM3Mzk4NTI1ZTY1ODkzZjNmMDFlNmNjZDc4ZjVlMjkwOWQ4MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P5aGWl-HmQ-LeZ1sYN0yOJdYzH-m9mFSZW2I8AGyNbk)

谢谢，我试试

发现问题所在了，我按照chatGpt给的代码引入的第三方jar包，在打包的时候没有打上，classNotFound了。

**Comment by yangfeng20** [comment]
@lt9 怎么样，是什么情况，没问题的话，我把issues关掉了哈

**Comment by lt9** [comment]
@yangfeng20 关了吧，没问题了。打包的时候没有打包第三方依赖的关系

**Comment by yangfeng20** [comment]
好哟
